from enum import Enum

class ConsentLevel(Enum):
    public = 'public'
    other = 'other'

class Nucleotide(Enum):
    A = 'A'
    C = 'C'
    G = 'G'
    T = 'T'
    U = 'U'
    N = 'N'

class AminoAcid(Enum):
    A = 'A'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    G = 'G'
    H = 'H'
    I = 'I'
    K = 'K'
    L = 'L'
    M = 'M'
    N = 'N'
    P = 'P'
    Q = 'Q'
    R = 'R'
    S = 'S'
    T = 'T'
    V = 'V'
    W = 'W'
    Y = 'Y'
    STAR = '*'

class FluRegion(Enum):
    HA = 'HA'
    NA = 'NA'
    NP = 'NP'
    MP = 'MP'
    PB1 = 'PB1'
    PB2 = 'PB2'
    NS = 'NS'
    PB1_F2 = 'PB1-F2'
    PA = 'PA'
    PA_X = 'PA-X'
    M1 = 'M1'
    M2 = 'M2'
    NS1 = 'NS1'
    NS2 = 'NS2'

class Codon(Enum):
    AAA = 'AAA'
    AAC = 'AAC'
    AAG = 'AAG'
    AAT = 'AAT'
    ACA = 'ACA'
    ACC = 'ACC'
    ACG = 'ACG'
    ACT = 'ACT'
    AGA = 'AGA'
    AGC = 'AGC'
    AGG = 'AGG'
    AGT = 'AGT'
    ATA = 'ATA'
    ATC = 'ATC'
    ATG = 'ATG'
    ATT = 'ATT'
    CAA = 'CAA'
    CAC = 'CAC'
    CAG = 'CAG'
    CAT = 'CAT'
    CCA = 'CCA'
    CCC = 'CCC'
    CCG = 'CCG'
    CCT = 'CCT'
    CGA = 'CGA'
    CGC = 'CGC'
    CGG = 'CGG'
    CGT = 'CGT'
    CTA = 'CTA'
    CTC = 'CTC'
    CTG = 'CTG'
    CTT = 'CTT'
    GAA = 'GAA'
    GAC = 'GAC'
    GAG = 'GAG'
    GAT = 'GAT'
    GCA = 'GCA'
    GCC = 'GCC'
    GCG = 'GCG'
    GCT = 'GCT'
    GGA = 'GGA'
    GGC = 'GGC'
    GGG = 'GGG'
    GGT = 'GGT'
    GTA = 'GTA'
    GTC = 'GTC'
    GTG = 'GTG'
    GTT = 'GTT'
    TAA = 'TAA'
    TAC = 'TAC'
    TAG = 'TAG'
    TAT = 'TAT'
    TCA = 'TCA'
    TCC = 'TCC'
    TCG = 'TCG'
    TCT = 'TCT'
    TGA = 'TGA'
    TGC = 'TGC'
    TGG = 'TGG'
    TGT = 'TGT'
    TTA = 'TTA'
    TTC = 'TTC'
    TTG = 'TTG'
    TTT = 'TTT'