"""add_wastewater_cols

Revision ID: 0932488c4377
Revises: 541c861117dd
Create Date: 2025-07-15 17:01:37.635418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0932488c4377'
down_revision: Union[str, None] = '541c861117dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('ww_viral_load', sa.Double(), nullable=True))
    op.add_column('samples', sa.Column('ww_catchment_population', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'ww_catchment_population')
    op.drop_column('samples', 'ww_viral_load')
    # ### end Alembic commands ###
