"""add_annotation_tables

Revision ID: 2d6cda68d97f
Revises: c9b71aa14630
Create Date: 2025-06-10 09:57:54.883491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6cda68d97f'
down_revision: Union[str, None] = 'c9b71aa14630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('effects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('species', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_effects')),
    sa.UniqueConstraint('detail', name='uq_detail')
    )
    op.create_table('papers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('publication_year', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papers')),
    sa.UniqueConstraint('author', 'publication_year', name='uq_title_and_year')
    )
    op.create_table('annotations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('amino_acid_substitution_id', sa.BigInteger(), nullable=False),
    sa.Column('effect_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['amino_acid_substitution_id'], ['amino_acid_substitutions.id'], name=op.f('fk_annotations_amino_acid_substitution_id_amino_acid_substitutions')),
    sa.ForeignKeyConstraint(['effect_id'], ['effects.id'], name=op.f('fk_annotations_effect_id_effects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotations')),
    sa.UniqueConstraint('amino_acid_substitution_id', 'effect_id', name='uq_substitution_and_effect')
    )
    op.create_table('annotations_papers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('annotation_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], name=op.f('fk_annotations_papers_annotation_id_annotations')),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_annotations_papers_paper_id_papers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotations_papers')),
    sa.UniqueConstraint('paper_id', 'annotation_id', name='uq_paper_annotation_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation_papers')
    op.drop_table('annotations_papers')
    op.drop_table('annotations')
    op.drop_table('papers')
    op.drop_table('effects')
    # ### end Alembic commands ###
