"""change_samples_lineages_uq_constraint

Revision ID: 317b417d3713
Revises: d4a3a311355b
Create Date: 2025-04-22 16:42:44.667748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317b417d3713'
down_revision: Union[str, None] = 'd4a3a311355b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lineages_samples_sample_lineage_pair', 'samples_lineages', type_='unique')
    op.create_index(op.f('ix_samples_lineages_lineage_id'), 'samples_lineages', ['lineage_id'], unique=False)
    op.create_unique_constraint('uq_samples_lineages_sample_id_lineage_id_is_consensus_call', 'samples_lineages', ['sample_id', 'lineage_id', 'is_consensus_call'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_samples_lineages_sample_id_lineage_id_is_consensus_call', 'samples_lineages', type_='unique')
    op.drop_index(op.f('ix_samples_lineages_lineage_id'), table_name='samples_lineages')
    op.create_unique_constraint('uq_lineages_samples_sample_lineage_pair', 'samples_lineages', ['sample_id', 'lineage_id'])
    # ### end Alembic commands ###
