"""nullable_samples_data

Revision ID: 4fec0d25e5b5
Revises: bee0f349ae96
Create Date: 2026-02-10 15:27:54.871774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fec0d25e5b5'
down_revision: Union[str, None] = 'bee0f349ae96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samples', 'bio_project',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'bio_sample_model',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'center_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'experiment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'instrument',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'platform',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'library_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'library_layout',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'library_selection',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'library_source',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'release_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('samples', 'creation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('samples', 'version',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'sample_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'sra_study',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'consent_level',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'assay_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'bases',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('samples', 'bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('samples', 'datastore_filetype',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'datastore_region',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'datastore_provider',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samples', 'datastore_provider',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'datastore_region',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'datastore_filetype',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('samples', 'bases',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('samples', 'assay_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'consent_level',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'sra_study',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'sample_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'version',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'creation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('samples', 'release_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('samples', 'library_source',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'library_selection',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'library_layout',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'library_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'platform',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'instrument',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'experiment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'center_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'bio_sample_model',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'bio_project',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
