"""collection_date_start_and_end

Revision ID: 68902446b545
Revises: caa58915b84c
Create Date: 2025-02-27 15:08:18.090506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from DB.models import Sample, AminoAcidSubstitution, Allele

# revision identifiers, used by Alembic.
revision: str = '68902446b545'
down_revision: Union[str, None] = 'caa58915b84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('collection_start_date', sa.Date(), nullable=True))
    op.add_column('samples', sa.Column('collection_end_date', sa.Date(), nullable=True))
    op.drop_column('samples', 'collection_date')
    # ### end Alembic commands ###

    for model in [Sample, Allele, AminoAcidSubstitution]:
        for name, table, sqltext in model.get_check_constraints_for_alembic():
            op.execute(f'ALTER TABLE {table} DROP CONSTRAINT IF EXISTS "{name}"')
            op.create_check_constraint(name, table, sqltext)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('collection_date', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('samples', 'collection_end_date')
    op.drop_column('samples', 'collection_start_date')
    # ### end Alembic commands ###
