"""uq_effects_detail

Revision ID: 795612f65fcb
Revises: b8de7e958227
Create Date: 2025-07-08 14:04:22.992021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795612f65fcb'
down_revision: Union[str, None] = 'b8de7e958227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_effects_detail', 'effects', ['detail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_effects_detail', 'effects', type_='unique')
    # ### end Alembic commands ###
