"""lineage_hierarchy

Revision ID: 7de5f65555c2
Revises: 541c861117dd
Create Date: 2025-09-11 16:42:30.273126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import DB.models

# revision identifiers, used by Alembic.
revision: str = '7de5f65555c2'
down_revision: Union[str, None] = '541c861117dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineages_immediate_children',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('child_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('parent_id <> child_id', name=op.f('ck_lineages_immediate_children_`no_self_parenthood`')),
    sa.ForeignKeyConstraint(['child_id'], ['lineages.id'], name=op.f('fk_lineages_immediate_children_child_id_lineages')),
    sa.ForeignKeyConstraint(['parent_id'], ['lineages.id'], name=op.f('fk_lineages_immediate_children_parent_id_lineages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineages_immediate_children')),
    sa.UniqueConstraint('parent_id', 'child_id', name='uq_lineages_immediate_children_parent_child')
    )
    # ### end Alembic commands ###

    op.execute(sqltext=DB.models.SqlSnippets.create_view_lineages_deep_children)
    op.execute(sqltext=DB.models.SqlSnippets.create_function_check_cyclic_lineage)
    op.execute(sqltext=DB.models.SqlSnippets.create_trigger_check_cyclic_lineage)
    op.execute(sqltext=DB.models.SqlSnippets.create_function_check_cross_system_lineage)
    op.execute(sqltext=DB.models.SqlSnippets.create_trigger_check_cross_system_lineage)


def downgrade() -> None:
    op.execute(sqltext=DB.models.SqlSnippets.drop_trigger_check_cross_system_lineage)
    op.execute(sqltext=DB.models.SqlSnippets.drop_function_check_cross_system_lineage)
    op.execute(sqltext=DB.models.SqlSnippets.drop_trigger_check_cyclic_lineage)
    op.execute(sqltext=DB.models.SqlSnippets.drop_function_check_cyclic_lineage)
    op.execute(sqltext=DB.models.SqlSnippets.drop_view_lineages_deep_children)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineages_immediate_children')
    # ### end Alembic commands ###
