"""clean_up_samples_cols

Revision ID: 8c3ed3c1128a
Revises: 7f0398098839
Create Date: 2026-02-27 11:36:48.282835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c3ed3c1128a'
down_revision: Union[str, None] = '7f0398098839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samples', 'bio_project',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'bio_sample_model',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'center_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'experiment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'instrument',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'platform',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'library_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'library_layout',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'library_selection',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'library_source',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'release_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('samples', 'creation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('samples', 'sample_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'sra_study',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'assay_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('samples', 'bases',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('samples', 'datastore_filetype')
    op.drop_column('samples', 'consent_level')
    op.drop_column('samples', 'version')
    op.drop_column('samples', 'datastore_provider')
    op.drop_column('samples', 'bytes')
    op.drop_column('samples', 'datastore_region')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('datastore_region', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('samples', sa.Column('bytes', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('samples', sa.Column('datastore_provider', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('samples', sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('samples', sa.Column('consent_level', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('samples', sa.Column('datastore_filetype', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('samples', 'bases',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('samples', 'assay_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'sra_study',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'sample_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'creation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('samples', 'release_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('samples', 'library_source',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'library_selection',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'library_layout',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'library_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'platform',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'instrument',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'experiment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'center_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'bio_sample_model',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('samples', 'bio_project',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
