"""add structural annotations table

Revision ID: b1c99efe02a8
Revises: 68d40db9995c
Create Date: 2026-07-01 05:23:22.155548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c99efe02a8'
down_revision: Union[str, None] = '68d40db9995c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structural_annotations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sequential_site', sa.Integer(), nullable=False),
    sa.Column('protein_name', sa.Text(), nullable=False),
    sa.Column('structural_note', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_structural_annotations')),
    sa.UniqueConstraint('protein_name', 'sequential_site')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structural_annotations')
    # ### end Alembic commands ###
