"""Add indices

Revision ID: b8ad6e225ead
Revises: 02f6fc29c769
Create Date: 2025-03-31 16:20:47.351415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ad6e225ead'
down_revision: Union[str, None] = '02f6fc29c769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_intra_host_variants_allele_id'), 'intra_host_variants', ['allele_id'], unique=False)
    op.create_index(op.f('ix_translations_amino_acid_substitution_id'), 'translations', ['amino_acid_substitution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_amino_acid_substitution_id'), table_name='translations')
    op.drop_index(op.f('ix_intra_host_variants_allele_id'), table_name='intra_host_variants')
    # ### end Alembic commands ###
