"""fix_col_names_in_pheno_metrics

Revision ID: b9f1f4a2db2c
Revises: a3e56fe3ae34
Create Date: 2026-03-03 14:38:10.626526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from DB.models import PhenotypeMetric

# revision identifiers, used by Alembic.
revision: str = 'b9f1f4a2db2c'
down_revision: Union[str, None] = 'a3e56fe3ae34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phenotype_metrics', sa.Column('phenotype_metric_name', sa.Text(), nullable=False))
    op.add_column('phenotype_metrics', sa.Column('phenotype_metric_assay_type', sa.Text(), nullable=False))
    op.drop_constraint('uq_phenotype_metrics_name', 'phenotype_metrics', type_='unique')
    op.create_unique_constraint('uq_phenotype_metrics_name', 'phenotype_metrics', ['phenotype_metric_name'])
    op.drop_column('phenotype_metrics', 'assay_type')
    op.drop_column('phenotype_metrics', 'name')
    # ### end Alembic commands ###

    for model in [PhenotypeMetric]:
            for name, table, sqltext in model.get_check_constraints_for_alembic():
                op.execute(f'ALTER TABLE {table} DROP CONSTRAINT IF EXISTS "{name}"')
                op.create_check_constraint(name, table, sqltext)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phenotype_metrics', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('phenotype_metrics', sa.Column('assay_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_phenotype_metrics_name', 'phenotype_metrics', type_='unique')
    op.create_unique_constraint('uq_phenotype_metrics_name', 'phenotype_metrics', ['name'])
    op.drop_column('phenotype_metrics', 'phenotype_metric_assay_type')
    op.drop_column('phenotype_metrics', 'phenotype_metric_name')
    # ### end Alembic commands ###
