"""add_census_region_+_epiweek

Revision ID: bd2964500cbf
Revises: 7f0398098839
Create Date: 2025-08-26 20:51:11.556966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd2964500cbf'
down_revision: Union[str, None] = '7f0398098839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('ww_epiweek', sa.Integer(), nullable=True))
    op.add_column('samples', sa.Column('ww_census_region', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'ww_census_region')
    op.drop_column('samples', 'ww_epiweek')
    # ### end Alembic commands ###