"""init

Revision ID: c9f647521b3c
Revises: 
Create Date: 2025-02-12 16:20:57.362108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from DB.enums import IntEnum, FluRegion, Nucleotide, AminoAcid, ConsentLevel

# revision identifiers, used by Alembic.
revision: str = 'c9f647521b3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alleles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region', IntEnum(FluRegion), nullable=False),
    sa.Column('position_nt', sa.BigInteger(), nullable=False),
    sa.Column('alt_nt', IntEnum(Nucleotide), nullable=True),
    sa.Column('alt_nt_indel', sa.Text(), nullable=True),
    sa.Column('position_aa', sa.BigInteger(), nullable=True),
    sa.Column('ref_aa', IntEnum(AminoAcid), nullable=True),
    sa.Column('alt_aa', IntEnum(AminoAcid), nullable=True),
    sa.Column('gff_feature', sa.Text(), nullable=True),
    sa.CheckConstraint("alt_nt_indel <> ''", name=op.f('ck_alleles_`alt_nt_indel_not_empty`')),
    sa.CheckConstraint("gff_feature <> ''", name=op.f('ck_alleles_`gff_feature_not_empty`')),
    sa.CheckConstraint('alt_aa between 0 and 20', name=op.f('ck_alleles_`alt_aa_in_range_of_enum_AminoAcid`')),
    sa.CheckConstraint('alt_nt between 0 and 16', name=op.f('ck_alleles_`alt_nt_in_range_of_enum_Nucleotide`')),
    sa.CheckConstraint('num_nulls(alt_nt, alt_nt_indel) = 1', name=op.f('ck_alleles_`must_have_nt_alt_xor_indel`')),
    sa.CheckConstraint('ref_aa between 0 and 20', name=op.f('ck_alleles_`ref_aa_in_range_of_enum_AminoAcid`')),
    sa.CheckConstraint('region between 0 and 13', name=op.f('ck_alleles_`region_in_range_of_enum_FluRegion`')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alleles')),
    sa.UniqueConstraint('region', 'position_nt', 'alt_nt', 'alt_nt_indel', name='uq_alleles_nt_values', postgresql_nulls_not_distinct=True)
    )
    op.create_table('samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('accession', sa.Text(), nullable=False),
    sa.Column('consent_level', IntEnum(ConsentLevel), nullable=False),
    sa.CheckConstraint('consent_level between 0 and 1', name=op.f('ck_samples_`consent_level_in_range_of_enum_ConsentLevel`')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_samples'))
    )
    op.create_table('dms_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ferret_sera_escape', sa.Double(), nullable=False),
    sa.Column('stability', sa.Double(), nullable=False),
    sa.Column('allele_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['allele_id'], ['alleles.id'], name=op.f('fk_dms_results_allele_id_alleles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dms_results')),
    sa.UniqueConstraint('allele_id', name=op.f('uq_dms_results_allele_id'))
    )
    op.create_table('intra_host_variants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.BigInteger(), nullable=False),
    sa.Column('allele_id', sa.BigInteger(), nullable=False),
    sa.Column('ref_dp', sa.BigInteger(), nullable=False),
    sa.Column('alt_dp', sa.BigInteger(), nullable=False),
    sa.Column('alt_freq', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['allele_id'], ['alleles.id'], name=op.f('fk_intra_host_variants_allele_id_alleles')),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], name=op.f('fk_intra_host_variants_sample_id_samples')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intra_host_variants')),
    sa.UniqueConstraint('sample_id', 'allele_id', name='uq_intra_host_variants_sample_allele_pair')
    )
    op.create_table('mutations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.BigInteger(), nullable=False),
    sa.Column('allele_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['allele_id'], ['alleles.id'], name=op.f('fk_mutations_allele_id_alleles')),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], name=op.f('fk_mutations_sample_id_samples')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mutations')),
    sa.UniqueConstraint('sample_id', 'allele_id', name='uq_mutations_sample_allele_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mutations')
    op.drop_table('intra_host_variants')
    op.drop_table('dms_results')
    op.drop_table('samples')
    op.drop_table('alleles')
    # ### end Alembic commands ###
