"""factor_out_geo_location

Revision ID: caa58915b84c
Revises: 232f6e55a160
Create Date: 2025-02-26 12:14:12.172725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa58915b84c'
down_revision: Union[str, None] = '232f6e55a160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_locations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('continent_name', sa.Text(), nullable=True),
    sa.Column('country_name', sa.Text(), nullable=True),
    sa.Column('region_name', sa.Text(), nullable=True),
    sa.Column('locality_name', sa.Text(), nullable=True),
    sa.Column('geo_center_lon', sa.Double(), nullable=True),
    sa.Column('geo_center_lat', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geo_locations')),
    sa.UniqueConstraint('country_name', 'region_name', 'locality_name', name='uq_geo_locations_country_name_region_name_locality_name', postgresql_nulls_not_distinct=True)
    )
    op.add_column('samples', sa.Column('geo_location_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_samples_geo_location_id_geo_locations'), 'samples', 'geo_locations', ['geo_location_id'], ['id'])
    op.drop_column('samples', 'geo_loc_name_country')
    op.drop_column('samples', 'geo_loc_name')
    op.drop_column('samples', 'geo_loc_name_country_continent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('geo_loc_name_country_continent', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('samples', sa.Column('geo_loc_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('samples', sa.Column('geo_loc_name_country', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_samples_geo_location_id_geo_locations'), 'samples', type_='foreignkey')
    op.drop_column('samples', 'geo_location_id')
    op.drop_table('geo_locations')
    # ### end Alembic commands ###
