"""uq_constraint_samples_accession

Revision ID: d449da42c7ca
Revises: c9b71aa14630
Create Date: 2025-06-18 15:26:38.501771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd449da42c7ca'
down_revision: Union[str, None] = 'c9b71aa14630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_samples_accession', 'samples', ['accession'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_samples_accession', 'samples', type_='unique')
    # ### end Alembic commands ###
