"""add_lineage_tables

Revision ID: d4a3a311355b
Revises: 52a080835cbc
Create Date: 2025-04-09 10:32:29.185497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a3a311355b'
down_revision: Union[str, None] = '52a080835cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineage_systems',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lineage_system_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineage_systems')),
    sa.UniqueConstraint('lineage_system_name', name='uq_lineage_systems_name')
    )
    op.create_table('lineages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lineage_system_id', sa.BigInteger(), nullable=False),
    sa.Column('lineage_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lineage_system_id'], ['lineage_systems.id'], name=op.f('fk_lineages_lineage_system_id_lineage_systems')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineages')),
    sa.UniqueConstraint('lineage_system_id', 'lineage_name', name='uq_lineages_name_uq_within_system')
    )
    op.create_table('samples_lineages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.BigInteger(), nullable=False),
    sa.Column('lineage_id', sa.BigInteger(), nullable=False),
    sa.Column('abundance', sa.Float(), nullable=True),
    sa.Column('is_consensus_call', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(abundance is null) = is_consensus_call', name=op.f('ck_samples_lineages_`has_abundance_xor_is_consensus`')),
    sa.ForeignKeyConstraint(['lineage_id'], ['lineages.id'], name=op.f('fk_samples_lineages_lineage_id_lineages')),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], name=op.f('fk_samples_lineages_sample_id_samples')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_samples_lineages')),
    sa.UniqueConstraint('sample_id', 'lineage_id', name='uq_lineages_samples_sample_lineage_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samples_lineages')
    op.drop_table('lineages')
    op.drop_table('lineage_systems')
    # ### end Alembic commands ###
