#!/bin/bash

export PGPASSWORD="$POSTGRES_PASSWORD"
NEW_PASS_HASH=$(echo "$MUNINN_DB_READONLY_PASSWORD" | python3 /muninn/bin/scram.py)
psql -d "$POSTGRES_DB"  -U "$POSTGRES_USER" \
-c "CREATE USER $MUNINN_DB_READONLY_USER WITH PASSWORD '$NEW_PASS_HASH';" \
-c "GRANT pg_read_all_data TO $MUNINN_DB_READONLY_USER;"

unset PGPASSWORD